apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-system
resources:
  - preview-janitor-rbac.yaml
  - preview-janitor-cronjob.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: paved-road
      app.kubernetes.io/managed-by: gitops
    includeSelectors: false
